卒業試験：README提出_add
pakira-56A/aruaru-game pull request #52
Opened 2024-10-03 11:55 UTC by pakira-56A

Wi-fiルーター故障により、プルリクにコメントをする時間がありませんでした。
申し訳ありません
READMEがながくなりましたが、確認をお願いいたします
by 閉店間際のカフェ

2024-10-04 03:52 UTC, Tsuchiya2 commented
対応ありがとうございます。以下の点に関してコメントします。
回答及びREADME.mdへの反映をお願いします。

---

サービスの分類として、ゲーム＋コミュニケーションツールとして認識しました。
ゲーム系の場合、1度完成してしまうと、その後の継続的な開発が難しいことが多々あります。MVP,本リリースに記載されている機能以外で、追加サービスの案や追加機能の案をREADME.mdに別途項目を設けても良いので記載をお願いします。（開発継続性があるかの観点から）

2024-10-04 09:55 UTC, pakira-56A commented
お疲れ様です、確認ありがとうございました！
追記いたしましたので、確認お願いいたします。
以下が追記したものになります
______
## 開発継続性を高める追加サービス案
**タグ付け**
- 投稿したあるあるの界隈にタグ付け機能を追加
- タグを辿ると、少し近い界隈のあるあるで遊んで・知って・シェアできます


**プッシュ通知**
- プッシュ通知機能をON/IFF設定で切り替えられる
- ONにした場合の詳細（以下、ユーザーは個別にON/OF設定ができる）
  - **タグの新着を通知**
    - よく見ているタグ上位３つを自動的に、または通知させたいタグの３つ選択させます
    - そのタグをつけた界隈の投稿が、新たにされるとプッシュ通知が届きます
    - 届いたプッシュ通知をタップすると、すぐ遊べます
  - **コメント・いいねをされた際の通知**
    - AI生成させたあるある・投稿したあるあるに、コメント/いいねがあると通知
      - ユーザーはコメント・いいね・両方を通知するか個別で選択できます

**季節イベントを開催**
- 数ヶ月に一度、季節に関するテーマで縛ったイベントを開催
- 例：１・２月開催イベントならば、テーマは`正月` `バレンタイン`等にちなんだあるあるをユーザーに募ります 
- テーマ自体に関するあるあるを生成/投稿するも良し
- 「〇〇(推し)のバレンタインイベント」等と題した（期間を絞った）界隈のあるある生成/投稿をしてもらうもよし
  - 「去年はあーだったのに、今年はこーですねw」と交流してもらうのも狙い
 ____

2024-10-05 01:47 UTC, Mariko222 commented
ご確認ありがとうございます。
追記内容に関しまして、概ね良いかと思います。
以下、気になった点のコメントになります。
***
神経衰弱は通常めくったカードで同じ数字が揃うと獲得できる、といったルールだと思います。
こちらのサービスでは何をもって揃うという概念なのか、どのような流れでゲームが進むのかを大まかにで構いませんのでご説明いただきたいです。
よろしくお願いします。

2024-10-05 03:59 UTC, pakira-56A commented
提出したREADMEにも書いてますが、生成/投稿されたあるあるは文字列でトランプに反映させます
- 1回目提出  
[![Image from Gyazo](https://i.gyazo.com/6df9703633fbca21736eb9dcab5bde3d.png)](https://gyazo.com/6df9703633fbca21736eb9dcab5bde3d)
- 2回目提出  
[![Image from Gyazo](https://i.gyazo.com/88cad8f4e60c562a726d3e992a91f6ef.png)](https://gyazo.com/88cad8f4e60c562a726d3e992a91f6ef)

そして既存のトップページの`遊び方`にもイメージを配置しています
[![Image from Gyazo](https://i.gyazo.com/28cf8d7fe973ec85455c6984084259f5.png)](https://gyazo.com/28cf8d7fe973ec85455c6984084259f5)


さらに詳しくREADMEに追記した内容は下記です。ご確認ください。

ただ、再提出の際に書いた案も含め
実装する機能の案が多すぎて、完成する自信がないです。
____
## 当サービスにおける神経衰弱カードの特徴  
上記にも記しましたが、当サービスで使うトランプカードの表面には  
AIで生成したあるある５つ、またはユーザーが投稿したあるある５つの**文字列**  
（本リリースに向けてはユーザーの任意で画像にカスタム可能）を印字・反映させ。  
プレイ画面のスタート時には１０枚のカードが裏返しで表示、めくるとあるあるを書いた文字列が表示されます  

### あるある文字列に関して
- １つのあるあるで２０文字前後を想定しています
- ５つのあるあるはそれぞれ、違う色の文字で表示させます
- めくった瞬間はカードの表面をドアップに表示（非同期）
  - スマホ画面でもあるあるを読みやすく・認識しやすくします
  - タップすると、元の10枚のカードが並んだ画面へ戻る（非同期）
- `あるある１`と`あるある１`を同じターンでめくればペア完成


既存のトップページの`遊び方`にもイメージを配置しています  
[![Image from Gyazo](https://i.gyazo.com/28cf8d7fe973ec85455c6984084259f5.png)](https://gyazo.com/28cf8d7fe973ec85455c6984084259f5)


### 画像にカスタム（本リリースに向けて、余裕があれば追加するかもしれない案）  
  
**１.カードの背面をカスタム**  
- ユーザーの任意で、カードの背面を投稿した界隈にちなんだ画像に変更できます

**２.あるあるの文字列をカスタム**  
- ユーザーの任意で、投稿したあるあるにちなんだ画像に変更できます
  - ５つのあるあるに各自にカスタム、または１枚の画像で５つのあるあるをカスタムかも選べます。
- カードをめくった瞬間、カードの表面をドアップに表示（非同期）
  - カードの表面は、カスタムした画像と、そのカードのあるある(文字列)を表示
  - タップすると元の10枚のカードが並んだ画面へ戻る（非同期）
____

2024-10-05 04:15 UTC, pakira-56A commented
提出したREADMEにも書いてますが、生成/投稿されたあるあるは文字列でトランプに反映させます
- 1回目提出  
[![Image from Gyazo](https://i.gyazo.com/6df9703633fbca21736eb9dcab5bde3d.png)](https://gyazo.com/6df9703633fbca21736eb9dcab5bde3d)
- 2回目提出  
[![Image from Gyazo](https://i.gyazo.com/88cad8f4e60c562a726d3e992a91f6ef.png)](https://gyazo.com/88cad8f4e60c562a726d3e992a91f6ef)

そして既存のトップページの`遊び方`にもイメージを配置しています
[![Image from Gyazo](https://i.gyazo.com/28cf8d7fe973ec85455c6984084259f5.png)](https://gyazo.com/28cf8d7fe973ec85455c6984084259f5)


さらに詳しくREADMEに追記した内容は下記です。ご確認ください。

ただ、再提出の際に書いた案も含め
実装する機能の案が多すぎて、技術的にも時間的にも完成する自信がないです。(卒業日は翌1/10)
完成させたいけど、これ全部実装は正直気力失せてきそうです。
____
## 当サービスにおける神経衰弱カードの特徴  
上記にも記しましたが、当サービスで使うトランプカードの表面には  
AIで生成したあるある５つ、またはユーザーが投稿したあるある５つの**文字列**  
（本リリースに向けてはユーザーの任意で画像にカスタム可能）を印字・反映させ。  
プレイ画面のスタート時には１０枚のカードが裏返しで表示、めくるとあるあるを書いた文字列が表示されます  

### あるある文字列に関して
- １つのあるあるで２０文字前後を想定しています
- ５つのあるあるはそれぞれ、違う色の文字で表示させます
- めくった瞬間はカードの表面をドアップに表示（非同期）
  - スマホ画面でもあるあるを読みやすく・認識しやすくします
  - タップすると、元の10枚のカードが並んだ画面へ戻る（非同期）
- `あるある１`と`あるある１`を同じターンでめくればペア完成


既存のトップページの`遊び方`にもイメージを配置しています  
[![Image from Gyazo](https://i.gyazo.com/28cf8d7fe973ec85455c6984084259f5.png)](https://gyazo.com/28cf8d7fe973ec85455c6984084259f5)


### 画像にカスタム（本リリースに向けて、余裕があれば追加するかもしれない案）  
  
**１.カードの背面をカスタム**  
- ユーザーの任意で、カードの背面を投稿した界隈にちなんだ画像に変更できます

**２.あるあるの文字列をカスタム**  
- ユーザーの任意で、投稿したあるあるにちなんだ画像に変更できます
  - ５つのあるあるに各自にカスタム、または１枚の画像で５つのあるあるをカスタムかも選べます。
- カードをめくった瞬間、カードの表面をドアップに表示（非同期）
  - カードの表面は、カスタムした画像と、そのカードのあるある(文字列)を表示
  - タップすると元の10枚のカードが並んだ画面へ戻る（非同期）
____

2024-10-05 04:17 UTC, pakira-56A commented
提出したREADMEにも書いてますが、生成/投稿されたあるあるは文字列でトランプに反映させます
- 1回目提出  
[![Image from Gyazo](https://i.gyazo.com/6df9703633fbca21736eb9dcab5bde3d.png)](https://gyazo.com/6df9703633fbca21736eb9dcab5bde3d)
- 2回目提出  
[![Image from Gyazo](https://i.gyazo.com/88cad8f4e60c562a726d3e992a91f6ef.png)](https://gyazo.com/88cad8f4e60c562a726d3e992a91f6ef)

そして既存のトップページの`遊び方`にもイメージを配置しています
[![Image from Gyazo](https://i.gyazo.com/28cf8d7fe973ec85455c6984084259f5.png)](https://gyazo.com/28cf8d7fe973ec85455c6984084259f5)


さらに詳しくREADMEに追記した内容は下記です。
ここにも記載したかったんですが、文字数が多いせいか送信できなかったのでスクショです
ご確認ください。

ただ、再提出の際に書いた案も含め
実装する機能の案が多すぎて、技術的にも時間的にも完成する自信がないです。(卒業日は翌1/10)
完成させたいけど、これ全部実装は正直気力失せてきそうです。
____
[![Image from Gyazo](https://i.gyazo.com/58a4d16bbddcc28fa60f4d8703fb527f.png)](https://gyazo.com/58a4d16bbddcc28fa60f4d8703fb527f)
[![Image from Gyazo](https://i.gyazo.com/7adf974ead6972b0fbc13e8e51acdd25.png)](https://gyazo.com/7adf974ead6972b0fbc13e8e51acdd25)
[![Image from Gyazo](https://i.gyazo.com/a7b51797ff7fecd2d5f73729301795c7.png)](https://gyazo.com/a7b51797ff7fecd2d5f73729301795c7)

____

2024-10-06 02:59 UTC, tarakish requested changes
ご確認と追加の説明ありがとうございます。確認しました👍️

> 実装する機能の案が多すぎて、技術的にも時間的にも完成する自信がないです。(卒業日は翌1/10)
完成させたいけど、これ全部実装は正直気力失せてきそうです。

MVPリリースに関しては、こちらのサービスが提供する価値はなにかというところからその価値の実現に必要な部分のみに絞って実装することである程度軽減できると思います。
例えばですが、界隈あるある生成・神経衰弱ゲーム・投稿などが価値なのであれば、Googleログイン、ブックマーク機能、動的OGPなどは本リリースに回しても良いかと思います。（この場合はユーザーと投稿が紐づけないので荒らし投稿などがあった場合ご自身で削除するか、それを防止する仕組みなどは必要になってくるかと思います）

#### 追加で確認したいこと
入力されたキーワードからAIであるあるを5つ提示するところに関しては技術検証はお済みでしょうか？
また、AIでのあるある生成に関してどの技術を使うかの記載もお願いします！

2024-10-06 03:15 UTC, pakira-56A commented
> 追加で確認したいこと  
> 入力されたキーワードからAIであるあるを5つ提示するところに関しては技術検証はお済みでしょうか？  
> また、AIでのあるある生成に関してどの技術を使うかの記載もお願いします！  

**OpenAI API**を使おうかと思います
- まだ何も詳しく調査はできてませんが「プロンプトを日本語で送信でき、日本語で返ってくる」と聞いています
- 何度か試し、理想の返しが来たプロンプトはこちらです  
[![Image from Gyazo](https://i.gyazo.com/8af10083416fe4b832219cf2a9539c59.png)](https://gyazo.com/8af10083416fe4b832219cf2a9539c59)

2024-10-07 03:36 UTC, tmtkzk0823 commented
上記確認しました。
技術検証も問題ないかと思います。

> 実装する機能の案が多すぎて、技術的にも時間的にも完成する自信がないです。

こちらについて私からもコメントさせていただきますね。
READMEの内容、追加機能案は現状の内容でいいかと思います。
MVPをどこまで実装するかですが、奥田さんのアプリのメイン機能は「AIで作成したあるあるの言葉で神経衰弱ができる」機能になるかと思うので、MVPはこの要件を満たす、以下の部分で設定いただいていいかと思いましたがいかがでしょうか？
```
- **AI生成機能**
  - ユーザーが入力した界隈(インスタンス変数に格納)をAIに渡し、あるあるを生成
  - あのあるある(文字列)をトランプに反映させ、神経衰弱に。
- **界隈あるある投稿機能**
  - AIではなくユーザー自ら界隈と、そのあるあるを投稿。
- **投稿した/された界隈あるあるを神経衰弱に反映**
  - ユーザーAが投稿した界隈あるあるで遊べる・Xシェアできる（可能ならMVPは**静的OGP**を実装）
  - ユーザーAがXシェアポストのリンクから飛んだユーザーBが、Xシェアされた界隈あるあるで遊べる
```
 
上記以外の実装は、本リリース欄に記述していただき、再度講師との面談等で本リリースに向けてどの機能を実装していくかを検討していただいてもいいかと思いました。（本リリース時は現状記載いただいている機能から2~3個を実装していただくイメージを持っていただければ良いかと）

レビュー内容を踏まえて、MVP時に実装する機能と本リリース時に実装する機能を再度見直していただき、READMEの修正をお願いしてももよろしいでしょうか？
よろしくお願いします。

2024-10-07 05:49 UTC, pakira-56A commented
@Tsuchiya2 
画面遷移図は大まかに完成し、早く提出したいです

レビューに関して、技術面談非対応の時間なので、こちらのコメントに記します
MVPは以下のメイン機能を優先すべきなのは分かります
> ```markdown
> - **AI生成機能**
>   - ユーザーが入力した界隈(インスタンス変数に格納)をAIに渡し、あるあるを生成
>   - あのあるある(文字列)をトランプに反映させ、神経衰弱に。
> - **界隈あるある投稿機能**
>   - AIではなくユーザー自ら界隈と、そのあるあるを投稿。
> - **投稿した/された界隈あるあるを神経衰弱に反映**
>   - ユーザーAが投稿した界隈あるあるで遊べる・Xシェアできる（可能ならMVPは**静的OGP**を実装）
>   - ユーザーAがXシェアポストのリンクから飛んだユーザーBが、Xシェアされた界隈あるあるで遊べる
> ```
ただこれらの機能を使ってもらう上で以下の、Google認証・Xシェア・動的0GPは必須のように思ってますが
省くべきですか？
```markdown
**Xでシェアするための機能**
- **Googleログイン**
- **Xシェア機能**
  - 作成した界隈のあるあるを保存し、Xでシェア
- **動的OGP**
  - Xシェアの際、動的OGPを反映させる
  - 動的OGPは、並んだカードが並んでおり。ユーザーが最初にめくったカードだけめくられた画像が理想。
```

そして、最初のレビューで土屋講師から
「**開発継続性を高める追加サービス案**を追記してください」と言われ、追記した案があります。
こちらもMVPリリース、本リリース時共に実装できると思えないので省きます
____

最終的に記載した機能一覧
[![Image from Gyazo](https://i.gyazo.com/55fe5cbf7c8609fe0da419ffc2f9f049.png)](https://gyazo.com/55fe5cbf7c8609fe0da419ffc2f9f049)
[![Image from Gyazo](https://i.gyazo.com/37b3653f2ffd6e3768d47ca730267134.png)](https://gyazo.com/37b3653f2ffd6e3768d47ca730267134)

2024-10-07 06:51 UTC, kenchasonakai commented
> 画面遷移図は大まかに完成してます、早く提出したいです

いままで対応してくださっていた講師のみなさんはよりよいアプリを作れるように、就活でアピールできるポイントを作れるようにアドバイスしてくださっていたと思うのですが、そのように言われてしまうと悲しいです

> ただこれらの機能を使ってもらう上で以下の、Google認証・Xシェア・動的0GPは必須のように思ってますが
省くべきですか？

ご自身で必須だと考えているのであれば作成していただいても構いません
issueベースの開発にて見積もりを行ってうえでMVPまでに何をやるのか、本リリース時までに何を作るのかを整理するとよいかなと思います

LGTMです！
次の課題に進んでください

2024-10-07 07:14 UTC, pakira-56A commented
すみませんでした。
中には既に提出分に書いてある内容に対して
再提出になった理由が書かれてないのもあり、どういう意図で何を狙って追記するべきだったのか曖昧なままでした。
_____
MVPリリース時はメイン機能を優先してつくり。
Google認証・Xシェア・動的0GP機能に着手するまでに余裕を持ち
スケジュール的に本リリースに回さずに済むよう、実装出来るように目指します。

LGTMありがとうございます！別ブランチにて修正した画面製図を提出させていただきます。
よろしくお願いします。

2024-10-07 09:24 UTC, merged